// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pings.sql

package ping

import (
	"context"
)

const list = `-- name: List :many
SELECT name, kind, first_seen_at, last_seen_at FROM pings ORDER BY name
`

func (q *Queries) List(ctx context.Context) ([]Ping, error) {
	rows, err := q.db.Query(ctx, list)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ping
	for rows.Next() {
		var i Ping
		if err := rows.Scan(
			&i.Name,
			&i.Kind,
			&i.FirstSeenAt,
			&i.LastSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsert = `-- name: Upsert :one
INSERT INTO pings (name, kind)
VALUES ($1, $2)
ON CONFLICT (name) DO UPDATE
    SET kind = EXCLUDED.kind,
        last_seen_at = now()
RETURNING name, kind, first_seen_at, last_seen_at
`

type UpsertParams struct {
	Name string `json:"name"`
	Kind string `json:"kind"`
}

func (q *Queries) Upsert(ctx context.Context, arg UpsertParams) (Ping, error) {
	row := q.db.QueryRow(ctx, upsert, arg.Name, arg.Kind)
	var i Ping
	err := row.Scan(
		&i.Name,
		&i.Kind,
		&i.FirstSeenAt,
		&i.LastSeenAt,
	)
	return i, err
}
