flowchart TD
    CUSTOMER[fa:fa-user Customer] --> API_INVITE[[POST /invites/$token/accept \n\napis.v1.invite.AcceptInvite]]

    subgraph API_SERVER
        API_INVITE --> INVITE_APP
    end

    subgraph INVITE_APP[fa:fa-gift Invite App]
        DOM_INVITE[fa:fa-id-card domains.invite.AcceptInvite] -->|Accept Invite| INVITE_SERVICE
        DOM_INVITE -->|Send Welcome Email| NOTIFICATION_SERVICE
        INVITE_SERVICE -->|Verify Invite Token| DATABASE
        INVITE_SERVICE -->|Update Security Profile| DATABASE
    end

    subgraph DATABASE[fa:fa-database Database]
        REPO_INVITE[fa:fa-envelope repositories.invites]
        REPO_SECURITY_PROFILE[fa:fa-lock repositories.security-profile]
    end

    subgraph INVITE_SERVICE[fa:fa-envelope Invite Service]
        SVC_INVITE[fa:fa-gift services.invite.AcceptInvite]
    end

    subgraph NOTIFICATION_SERVICE[fa:fa-envelope Notification Service]
        SVC_NOTIFY[fa:fa-envelope services.notifications.Notify]
    end
