apiVersion: batch/v1
kind: Job
metadata:
  name: migrate
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: migrate
          image: docker.io/migrate/migrate:v4.19.1
          args:
            - -path=/migrations
            - -database=postgres://hyrule_owner:hyrule_owner@hyrule-database:5432/hyrule?sslmode=disable
            - up
          volumeMounts:
            - name: migrations
              mountPath: /migrations
      volumes:
        - name: migrations
          configMap:
            name: hyrule-migrations
