app:
  fullnameOverride: iam-jwks

  image:
    repository: iamnande/iam-jwks
    tag: latest

  service:
    port: 8000

  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      memory: 128Mi

  env:
    HYRULE_HTTP_SERVER_ADDR: ":8000"
    HYRULE_REGION: us-east-2
    HYRULE_ENVIRONMENT: dev
    HYRULE_DATABASE_HOST: hyrule-database
    HYRULE_DATABASE_PORT: "5432"
    HYRULE_DATABASE_USER: hyrule_app_ro
    HYRULE_DATABASE_PASSWORD: hyrule_app_ro
    HYRULE_DATABASE_NAME: hyrule
    HYRULE_DATABASE_SSL_MODE: disable

platform: {}
