apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pings.fullname" . }}
  labels:
    {{- include "pings.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "pings.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "pings.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: pings
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
          env:
            {{- range $key, $value := .Values.env }}
            - name: HYRULE_{{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          startupProbe:
            httpGet:
              path: /startupz
              port: http
            failureThreshold: 30
            periodSeconds: 1
          livenessProbe:
            httpGet:
              path: /livez
              port: http
          readinessProbe:
            httpGet:
              path: /readyz
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
