// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
)

// Defines values for InvalidAttributeSource.
const (
	Body   InvalidAttributeSource = "body"
	Header InvalidAttributeSource = "header"
	Path   InvalidAttributeSource = "path"
	Query  InvalidAttributeSource = "query"
)

// Valid indicates whether the value is a known member of the InvalidAttributeSource enum.
func (e InvalidAttributeSource) Valid() bool {
	switch e {
	case Body:
		return true
	case Header:
		return true
	case Path:
		return true
	case Query:
		return true
	default:
		return false
	}
}

// Defines values for Kind.
const (
	App     Kind = "app"
	Host    Kind = "host"
	Service Kind = "service"
)

// Valid indicates whether the value is a known member of the Kind enum.
func (e Kind) Valid() bool {
	switch e {
	case App:
		return true
	case Host:
		return true
	case Service:
		return true
	default:
		return false
	}
}

// Defines values for State.
const (
	Stale State = "stale"
	Up    State = "up"
)

// Valid indicates whether the value is a known member of the State enum.
func (e State) Valid() bool {
	switch e {
	case Stale:
		return true
	case Up:
		return true
	default:
		return false
	}
}

// Error defines model for Error.
type Error struct {
	Code              string              `json:"code"`
	InvalidAttributes *[]InvalidAttribute `json:"invalid_attributes,omitempty"`
	Message           string              `json:"message"`
	Name              string              `json:"name"`
	OperationId       string              `json:"operation_id"`
}

// InvalidAttribute defines model for InvalidAttribute.
type InvalidAttribute struct {
	Path   string                 `json:"path"`
	Reason string                 `json:"reason"`
	Rule   string                 `json:"rule"`
	Source InvalidAttributeSource `json:"source"`
}

// InvalidAttributeSource defines model for InvalidAttribute.Source.
type InvalidAttributeSource string

// Kind defines model for Kind.
type Kind string

// Ping defines model for Ping.
type Ping struct {
	// FirstSeenAt when this name was first seen - i.e. when it registered.
	FirstSeenAt time.Time `json:"first_seen_at"`
	Kind        Kind      `json:"kind"`
	LastSeenAt  time.Time `json:"last_seen_at"`
	Name        string    `json:"name"`

	// State derived, not stored - up if last_seen_at is within the service's configured staleness window, stale otherwise.
	State State `json:"state"`
}

// PingRequest defines model for PingRequest.
type PingRequest struct {
	Kind Kind `json:"kind"`

	// Name the unique, self-chosen name of the thing pinging in.
	Name string `json:"name"`
}

// State derived, not stored - up if last_seen_at is within the service's configured staleness window, stale otherwise.
type State string

// BadRequest defines model for BadRequest.
type BadRequest = Error

// InternalServerError defines model for InternalServerError.
type InternalServerError = Error

// RecordPingJSONRequestBody defines body for RecordPing for application/json ContentType.
type RecordPingJSONRequestBody = PingRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// ListPings list everything registered
	// (GET /pings)
	ListPings(w http.ResponseWriter, r *http.Request)
	// RecordPing record a ping
	// (POST /pings)
	RecordPing(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// ListPings list everything registered
// (GET /pings)
func (_ Unimplemented) ListPings(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// RecordPing record a ping
// (POST /pings)
func (_ Unimplemented) RecordPing(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListPings operation middleware
func (siw *ServerInterfaceWrapper) ListPings(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListPings(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RecordPing operation middleware
func (siw *ServerInterfaceWrapper) RecordPing(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RecordPing(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/pings", wrapper.ListPings)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/pings", wrapper.RecordPing)
	})

	return r
}

type BadRequestJSONResponse Error

type InternalServerErrorJSONResponse Error

type ListPingsRequestObject struct {
}

type ListPingsResponseObject interface {
	VisitListPingsResponse(w http.ResponseWriter) error
}

type ListPings200JSONResponse []Ping

func (response ListPings200JSONResponse) VisitListPingsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListPings500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response ListPings500JSONResponse) VisitListPingsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type RecordPingRequestObject struct {
	Body *RecordPingJSONRequestBody
}

type RecordPingResponseObject interface {
	VisitRecordPingResponse(w http.ResponseWriter) error
}

type RecordPing200JSONResponse Ping

func (response RecordPing200JSONResponse) VisitRecordPingResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type RecordPing400JSONResponse struct{ BadRequestJSONResponse }

func (response RecordPing400JSONResponse) VisitRecordPingResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type RecordPing500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response RecordPing500JSONResponse) VisitRecordPingResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// ListPings list everything registered
	// (GET /pings)
	ListPings(ctx context.Context, request ListPingsRequestObject) (ListPingsResponseObject, error)
	// RecordPing record a ping
	// (POST /pings)
	RecordPing(ctx context.Context, request RecordPingRequestObject) (RecordPingResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// ListPings operation middleware
func (sh *strictHandler) ListPings(w http.ResponseWriter, r *http.Request) {
	var request ListPingsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListPings(ctx, request.(ListPingsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListPings")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListPingsResponseObject); ok {
		if err := validResponse.VisitListPingsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RecordPing operation middleware
func (sh *strictHandler) RecordPing(w http.ResponseWriter, r *http.Request) {
	var request RecordPingRequestObject

	var body RecordPingJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RecordPing(ctx, request.(RecordPingRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RecordPing")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RecordPingResponseObject); ok {
		if err := validResponse.VisitRecordPingResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
