// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: keys.sql

package key

import (
	"context"
)

const list = `-- name: List :many
SELECT id, algorithm, public_key, created_at FROM iam_jwks_keys ORDER BY created_at
`

func (q *Queries) List(ctx context.Context) ([]IamJwksKey, error) {
	rows, err := q.db.Query(ctx, list)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IamJwksKey
	for rows.Next() {
		var i IamJwksKey
		if err := rows.Scan(
			&i.ID,
			&i.Algorithm,
			&i.PublicKey,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
