// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package key

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type IamJwksKey struct {
	ID        string             `json:"id"`
	Algorithm string             `json:"algorithm"`
	PublicKey string             `json:"public_key"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
