global:
  image:
    registry: ""
  imagePullSecrets: []

nameOverride: ""
fullnameOverride: ""

# deployment | statefulset | daemonset | job | cronjob
mode: deployment

image:
  registry: ""
  repository: ""
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 1

serviceAccount:
  create: true
  name: ""
  annotations: {}

service:
  enabled: true
  type: ClusterIP
  port: 8000

probes:
  startup:
    enabled: true
    path: /startupz
  liveness:
    enabled: true
    path: /livez
  readiness:
    enabled: true
    path: /readyz

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    memory: 128Mi

env: {}
extraEnv: []
extraEnvFrom: []

extraVolumes: []
extraVolumeMounts: []
additionalContainers: []
initContainers: []
additionalServices: []

rbac:
  role:
    extraRules: []
