CREATE ROLE hyrule_app LOGIN PASSWORD 'hyrule_app';

GRANT CONNECT ON DATABASE hyrule TO hyrule_app;
GRANT USAGE ON SCHEMA public TO hyrule_app;

ALTER DEFAULT PRIVILEGES FOR ROLE hyrule_owner IN SCHEMA public
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO hyrule_app;
ALTER DEFAULT PRIVILEGES FOR ROLE hyrule_owner IN SCHEMA public
    GRANT USAGE, SELECT ON SEQUENCES TO hyrule_app;
